# Generated by Django 6.0.3 on 2026-04-02 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('idCours', models.BigAutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('duree', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('idRole', models.BigAutoField(primary_key=True, serialize=False)),
                ('nomRole', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RessourceCours',
            fields=[
                ('idRessource', models.BigAutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=500)),
                ('dateAjout', models.DateTimeField(auto_now_add=True)),
                ('idCours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cours')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('idUtilisateur', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('motDePasse', models.CharField(max_length=100)),
                ('dateNaissance', models.DateField()),
                ('idRole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.role')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('idLog', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('resultat', models.CharField(choices=[('succes', 'Succes'), ('echec', 'Echec')], max_length=20)),
                ('ipAdresse', models.CharField(max_length=100)),
                ('dateHeure', models.DateTimeField(auto_now_add=True)),
                ('idUtilisateur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='cours',
            name='idProfesseurResponsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.utilisateur'),
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('idInscription', models.BigAutoField(primary_key=True, serialize=False)),
                ('dateInscription', models.DateField()),
                ('idCours', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.cours')),
                ('idEtudiant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.utilisateur')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('idEtudiant', 'idCours'), name='unique_inscription_etudiant_cours')],
            },
        ),
    ]
